### ISSUE TITLE
MEJORAR LA VISTA CON GROSERY CRUD -ESTAN DENTRO DE ADMIN EJEMPLOS 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_bancos#1]
AL utilizar la herramienta grocery crud se mejota la vista para el usuario de esta forma tambien se obtiene:
* mejora en la exportacion de listados 
* filtros especificos por columnas 
* Sumatoria de totales por columnas 
---------------------------------------------------------------------------------------------
* la observacion es que : El total de del modulo bancos debe ser igual al modulo C X C (cuentas x cobrar)

**Comment by joshe091** [comment]
El listado esta implementado con grosery crud.
Se está ahora implementando el crud con joins, debido a que el listado de cheques se necesita extraer el nombre del banco y del cliente.
Necesito implementar JOIN LEFT, que no tengo conocimiento si el crud lo soporta.
Se continúa en pruebas.

**Comment by eychamba** [comment]
Si tiene esa opcion, Revisar: models/Grocery_join_model
en el parametro option envia el tipo de join.
Hacer estos cambios y subirlos para el d[ia lunes realizar la revision a fondo del modulo.

**Comment by joshe091** [comment]
Implementada la vista CRUD con joins y en las tablas correspondientes a cheques en custodio, excepto los cheques registrados, debido a que se requiere poner en la tabla los botones de confirmar y editar.
