### ISSUE TITLE
DETALLE EN DEPOSITO DE CHEQUES - PROTESTO DE CHEQUES 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_bancos#2]
Al realizar el deposito existe algunas recomendaciones como :
* La impresion del comprobante correctamente
* Detalle en la generacion del asiento contable con: nombre del cliente +  #factura
* Permitir del listado de cheques DEOSITADOS, se enlace a ver/editar comprobante y Protestar un cheque.
* Revisar que el cheque protestado se crea una cuenta por cobrar y se lista en el modulo de cuentas x cobrar.  
* Permitir visualizar el comprobante desde   cehques protestados 
* Revisar comprobante de cheque protestado que esta generando mAL EL ASIENTO CONTABLE

**Comment by joshe091** [comment]
Dos primeros puntos arreglados.
- Impresión correcta
- Detalle del asiento agregado el nombre del cliente.
En cuanto a #factura quiero saber de donde extraigo ese campo. En la tabla de cheques custodio tengo un 'doc_id'.

**Comment by joshe091** [comment]
Terminados todos los requerimientos del issue.
Queda corregir la impresión de comprobantes desde las nuevas ventanas.
Se pide comprobar el funcionamiento para realizar correcciones.

**Comment by edymac** [comment]
* revisar el comprobante sigue con pequeño problema ya que se cambian los asientos al hacer el deposito
* revisar que el comprobante de  chuqes proytestados esta duplicanco el valos con devolucion en venta s

**Comment by joshe091** [comment]
- Los datos se habían estado grabando bien, el problema estaba en las consultas, una vez detectado el error se ha corregido.
Solicito revisar para comprobar si aún existen problemas.

**Comment by edymac** [comment]
luego de revisar esta muy bien .. hay detalles q hay que seguir corrigiendo como:
* mostrar en venta sobre puesta los comprobantes 
* no se esta visualizando aun el comprobande desde conciliaciones 
* sacar DEPOSITOS Y CONCIALIACIONES fuera de CHEQUES

**Comment by joshe091** [comment]
Realizado lo solicitado. Pido verificar.
Pido agregar una restricción a los cheques, porque existen cheques en custodio sin numero de cheque, y se requiere ese dato imperativamente.
Es necesario que al momento de agregar un nuevo cheque custodio no se permita grabar sin este dato.

**Comment by edymac** [comment]
*en cheques depositados eata BIEN EL COMPROBANTE SOLO EL VALOR QUE LO LISTAS se resta al portestar un cheque y debe maneter el mismo valor 
* el comprobante de chjeque protestado debe tener el asineto contable real , bancos vs cuentas x cobrar y tenemos otrso valores , revisar porfavor

**Comment by joshe091** [comment]
Corregido, solicito hacer pruebas.

**Comment by joshe091** [comment]
Últimas correcciones sobre anulaciones de depositos y cheques subidas. No habia considerado como los cambios afectaban a las anulaciones.
Corregido, solicito pruebas para descartar más inconsistencias.
