### ISSUE TITLE
Actualizacion tabla cuenta bancaria

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_bancos#3]
1. la tabla bill_cuentabancaria debe quedar unicamente con los saldos iniciales de los bancos.
2. Actualizar los saldos de bill_cuentabancaria_saldos
3.Los pagos que estaban registrados en bill_cuentabancaria, estan en bill_cheque_pago, se debe realizar el proceso para agregar estos a los registros de cuentabancaria.
3 Los cheques de pago tienen un id que los relaciona con el comprobante de pago.
4. Algunos de los primeros asientos contables generados por el pago de una factura de compra estabaan registrandose en la tabla billing_contaasientocontable, entonces, para todas las transacciones Pago CxP (21) que no esten registradas en bill_asiento_contable, se debe crear dicho asiento, ojo que habria que comprar que no exista un asiento similar, mediante el tipo de transaccion y docid.

**Comment by joshe091** [comment]
Los dos primeros ítems están solucionados.
En el ticket no especificaba seleccionar cada cheque, sólo estaba realizar el proceso para agregarlos registros a la cuenta bancaria, por tanto está a nivel de base de datos en una sentencia sql realizado el proceso de:
1. ELIMINAR de bill_cuentabancaria todo excepto saldos iniciales.
2. ACTUALIZAR los saldos de las ctas en bill_cuentabancaria_saldos al saldo inicial.
3. REINGRESAR los cheques pagados a bill_cuentabancaria.

Las pruebas se las hizo  en una copia de la bd_test a nivel local.
Los querys están ya agregados en la bd_test, adjunto las sentencias aquí también para pruebas:
<code>
-- Suma de debitos, creditos y saldos de un banco

	SELECT cta.banco_id, b.nombre banco, SUM(cta.debito) TotalDebito, SUM(cta.credito) TotalCredito, SUM(cta.saldo) TotalSaldo
	FROM bill_cuentabancaria cta
	JOIN billing_banco b ON b.id = cta.banco_id
	GROUP BY banco;

<code>
-- RESET bill_cuentabancaria todo excepto saldos iniciales.

         DELETE FROM bill_cuentabancaria WHERE tipo_id!=4;


<code>
-- ACTUALIZAR los saldos de las ctas en bill_cuentabancaria_saldos al saldo inicial
<code>
 UPDATE bill_cuentabancaria_saldos cs
 SET saldo = 
  (
   SELECT cta.saldo 
   FROM bill_cuentabancaria cta
   WHERE cta.tipo_id = 4 AND  cta.banco_id = cs.banco_id
  );

<code>
SELECT * FROM bill_cuentabancaria AS cuentabancaria_antes;

<code>
-- Reingresar los cheques pagados a bill_cuentabancaria
<code>
INSERT INTO bill_cuentabancaria
	(banco_id,
	nombre_usuario,
	tipo_id,
	fecha_vence,
	fecha_registro,
	doc_id,
	tipo_transaccion,
	debito,
	saldo,
	anio,
	mes,
	empleado_id,
	proveedor_id,
	hora,
	estado)
SELECT 
	chp.banco_id, 
	nombre_beneficiario AS nombre_usuario, 
	'1' AS tipo_id, 
	fecha_cobro AS fecha_vence, 
	fecha_emision AS fecha_registro, 
	bcp.doc_id, 
	'02' AS tipo_transaccion,
	valor AS debito,
	(cs.saldo - valor) AS saldo, 
	EXTRACT(YEAR FROM fecha_emision) AS anio, 
	EXTRACT(MONTH FROM fecha_emision) AS mes,
	bcp.empleado_id, 
	bcp.proveedor_id, 
	hora_emision as hora, 
	'1' as estado
FROM bill_cheque_pago chp
JOIN bill_comprob_pago bcp ON bcp.id = chp.comprobante_id
JOIN bill_cuentabancaria_saldos cs ON cs.banco_id = chp.banco_id;

<code>
SELECT * FROM bill_cuentabancaria AS cuentabancaria_despues;

**Comment by joshe091** [comment]
Boton para reiniciar cuentas bancarias agregado al modulo correcciones.
Este boton elimina todos los registros o movimientos bancarios y deja las cuentas bancarias unicamente con los saldos iniciales. Ademas actualiza los saldos de cada cuenta.
Revisar.

**Comment by joshe091** [comment]
Rastreo de asientos a sus asientos contables, si tienen asiento tanto en la tabla antigua "billing_contaasientocontable" y en la nueva "bill_asiento_contable" se realizado, con un rastreo efectivo del cheque a su asiento contable.
Existen 91 cheques que no tienen registrado asiento contable en ninguna de las 2 tablas. Estos son desde el cheque 250 en adelante.
Solicito el asiento contable para registrarlo en estos cheques.
