### ISSUE TITLE
Correcciones Modulo Bancos

### ISSUE THREAD

**Issue by eychamba** [MASTERPC-CIA/bill_bancos#4]
1. Relacionar el cheque de pago con el banco correcto, estos cheques salen de las cuentas bancarias que posee la empresa.
2. Mejorar la vista de visualizacion de los cheques que se van a registras en las cuentas contables.
3. Agregar la opcion de filtrar por bancos y por estado del cheque.

**Comment by joshe091** [comment]
Requerimientos terminados. Solicito revisar.
